name: test-concur-pr-expr
on:
  workflow_call: {}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}::${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number) || github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hello"
