name: test-concurrency-workflow
on:
  workflow_call: {}
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}::${{ github.ref_name }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "hello from concurrency workflow"
