name: test-no-matrix
on:
  workflow_call: {}
  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-24.04
    outputs:
      required: ${{ steps.detect.outputs.required }}
    steps:
      - id: detect
        run: echo "required=false" >> "$GITHUB_OUTPUT"

  build:
    needs: metadata
    if: ${{ needs.metadata.outputs.required == 'true' }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
    steps:
      - run: echo "should be skipped"
